# configs/config.yaml

database:
  host: localhost          # Changed from 'db' to 'localhost'
  port: 5432
  user: postgres
  password: Secured$3211
  dbname: nuprc
  sslmode: disable

server:
  port: 8080

jwt:
  secret: drkatanga2020

exchange_rate_api_url: "https://openexchangerates.org/api/historical/%s.json"
exchange_rate_app_id: "939b6a724b35438e8f0ecfadf91f9c4f"